### ISSUE TITLE
Fortimanager Cloud

### ISSUE THREAD

**Issue by sebbbastien** [fortinetdev/terraform-provider-fortimanager#36]
Hi,

Please support Fortimanager Cloud as provider target.

**Comment by lix-fortinet** [comment]
Hi @sebbbastien,

The provider supports FortiManager Cloud since v1.9.0. Here is the reference of the Document: https://registry.terraform.io/providers/fortinetdev/fortimanager/latest/docs#clean_session:~:text=There%20are%20two%20kinds%20of%20credentials%20supported%20for%20FortiManager%20Cloud. 

We will close this issue since it has been fixed. Feel free to open a new issue if you have any questions.

Thanks,
Xing
