### ISSUE TITLE
Error Installation on DESTROY and UPDATE SECTION RESOURCE

### ISSUE THREAD

**Issue by Kakakaz75** [fortinetdev/terraform-provider-fortimanager#42]
Hi all

we have a problem with install firewall policy on Fortigate by FortiManager with Destroy or update resource

So, on the creation process, we don't have any problem and the installation are ok
When we destroy the service, all configuration are erased on the FortiManager but they not on the Fortigate.

Please see the follow code about it

   **resource "fortimanager_securityconsole_install_package" "INST-PKG_Label" { 
	  depends_on = [ <Somethng> ]
	  fmgadom = var.Paramiters.ADom
	  pkg     = var.Paramiters.PolicyPackage
	  flags   = ["none"]
  }**

On the Update phase, we've found a follow workaroud

  **`resource "null_resource" "AlwaysRun" {
	  triggers = {
		  timestamp = "${timestamp()}"
	  }**
  }

  resource "fortimanager_securityconsole_install_package" "INST-PKG_Label" {
	  depends_on = [ <Somethng> ]
	  fmgadom = var.Paramiters.ADom
	  pkg     = var.Paramiters.PolicyPackage
	  flags   = ["none"]
	  **lifecycle {
		  replace_triggered_by = [ null_resource.AlwaysRun ]
		  }**	
  }
  `_

You have any idea to solve my situation
Thanks a lot
Maurizio

**Comment by MaxxLiu22** [comment]
Hi @Kakakaz75 ,

Thank you for your question, that is expected since Terraform operations(create update destroy) only manages the resources on FMG, and FMG applies the changes to FGT through ``fortimanager_securityconsole_install_package`` function. So if we want to apply the changes to FGT on every time we update FMG, we had better run  ``fortimanager_securityconsole_install_package`` on every time at the end of all resources updated by setting ``force_recreate    = uuid()``
```
resource "fortimanager_securityconsole_install_package" "trname" {
  fmgadom           = "root"
  flags             = ["none"]
  pkg               = "default"
  force_recreate    = uuid()
  depends_on = [fortimanager_resource.first, fortimanager_resource.second, ....] // make sure fortimanager_securityconsole_install_package runs in the last
}
```

if we want to destroy everything on FGT directly through FMG terraform, we just delete everything except ``fortimanager_securityconsole_install_package`` and apply again, obviously that is not a smart way than yours, Hope Terraform platform can provide a way to run a resource after run ``terraform destroy``.
Let me know if that doesn't solve your question.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi everyone,

I will proceed with closing this case. If you continue to experience any issues, please feel free to reopen it or open a new case.

Thank you,
Maxx
